name: continuos integration

on: 
  pull_request:
    branches: [ master ]

jobs:
  ci_to_master:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@
        with:
          node-version: 16
      - run: npm ci
      - run: npm test
      - run: npm run build
      