name: continuos integration

on: 
  push: 
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci_to_master:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16      
      - run: npm test
      - run: npm run build
